# Generated by Django 3.2.5 on 2021-08-18 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favourites',
        ),
        migrations.RemoveField(
            model_name='user',
            name='rate_listing',
        ),
    ]
