# Generated by Django 3.2.5 on 2021-08-19 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0002_auto_20210818_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='user',
            name='rate_listing',
            field=models.CharField(default='', max_length=200),
        ),
    ]
