# Generated by Django 3.2.5 on 2021-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Property', 'Property'), ('Cars', 'Cars'), ('Jobs', 'Jobs'), ('Mobiles', 'Mobiles'), ('Furniture', 'Furniture'), ('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics'), ('Fashion', 'Fashion'), ('Bikes', 'Bikes')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('MN', 'Manipur'), ('OD', 'Odisha'), ('RJ', 'Rajasthan'), ('WB', 'West Bengal'), ('MI', 'Sikkim'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('AS', 'Assam'), ('MH', 'Maharashtra'), ('TN', 'Tamil Nadu'), ('KA', 'Karnataka'), ('TS', 'Telegana'), ('CG', 'Chhattisgarh'), ('BR', 'Bihar'), ('JH', 'Jharkhand'), ('TR', 'Tripura'), ('PB', 'Punjab'), ('NL', 'Nagaland'), ('UK', 'Uttarakhand'), ('HP', 'Haryana'), ('UP', 'Uttar Pradesh'), ('MP', 'Madhya Pradesh'), ('AR', 'Arunachal Pradesh'), ('AP', 'Andhra Pradesh'), ('MZ', 'Mizoram'), ('ML', 'Meghalaya'), ('KL', 'Kerala')], max_length=100),
        ),
    ]
