# Generated by Django 3.2.5 on 2021-08-19 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20210819_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Cars', 'Cars'), ('Books&Sports', 'Books&Sports'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Property', 'Property'), ('Bikes', 'Bikes'), ('Furniture', 'Furniture'), ('Mobiles', 'Mobiles'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('HP', 'Haryana'), ('PB', 'Punjab'), ('AS', 'Assam'), ('MI', 'Sikkim'), ('WB', 'West Bengal'), ('OD', 'Odisha'), ('GJ', 'Gujarat'), ('AR', 'Arunachal Pradesh'), ('TS', 'Telegana'), ('MP', 'Madhya Pradesh'), ('NL', 'Nagaland'), ('RJ', 'Rajasthan'), ('BR', 'Bihar'), ('TN', 'Tamil Nadu'), ('MH', 'Maharashtra'), ('CG', 'Chhattisgarh'), ('JH', 'Jharkhand'), ('TR', 'Tripura'), ('KL', 'Kerala'), ('MN', 'Manipur'), ('GA', 'Goa'), ('MZ', 'Mizoram'), ('AP', 'Andhra Pradesh'), ('KA', 'Karnataka'), ('UK', 'Uttarakhand'), ('UP', 'Uttar Pradesh'), ('ML', 'Meghalaya')], max_length=100),
        ),
    ]
