# Generated by Django 3.2.5 on 2021-08-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20210819_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Mobiles', 'Mobiles'), ('Bikes', 'Bikes'), ('Cars', 'Cars'), ('Furniture', 'Furniture'), ('Property', 'Property'), ('Fashion', 'Fashion'), ('Jobs', 'Jobs'), ('Books&Sports', 'Books&Sports'), ('Electronics', 'Electronics')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listing',
            name='state',
            field=models.CharField(choices=[('CG', 'Chhattisgarh'), ('AS', 'Assam'), ('TN', 'Tamil Nadu'), ('MI', 'Sikkim'), ('KA', 'Karnataka'), ('UP', 'Uttar Pradesh'), ('HP', 'Haryana'), ('BR', 'Bihar'), ('UK', 'Uttarakhand'), ('MZ', 'Mizoram'), ('KL', 'Kerala'), ('OD', 'Odisha'), ('WB', 'West Bengal'), ('JH', 'Jharkhand'), ('AP', 'Andhra Pradesh'), ('TR', 'Tripura'), ('NL', 'Nagaland'), ('TS', 'Telegana'), ('MH', 'Maharashtra'), ('PB', 'Punjab'), ('ML', 'Meghalaya'), ('MP', 'Madhya Pradesh'), ('GA', 'Goa'), ('GJ', 'Gujarat'), ('RJ', 'Rajasthan'), ('MN', 'Manipur'), ('AR', 'Arunachal Pradesh')], max_length=100),
        ),
    ]
